window.PRICE_DATA = {
  range: { minKg: 0.5, maxKg: 80 },
  carriers: [
    {
      id: "sf",
      name: "顺丰",
      shortName: "SF",
      color: "#6b7280",
      formula: "first-to-threshold",
      ruleLabel: "首重40斤 / 40-120斤 / 120斤以上",
      source: "b9876bfd43c0ad6690944be2eb0f78f8.jpg",
      under20Source: "IMG_9436.HEIC",
      under20Rows: [
        sfUnder20("sfu-hubei-wuhan", "湖北", "武汉（同城）", "specific", 6.5, 0.7, null, null, 0.5, 0.9, ["武汉"]),
        sfUnder20("sfu-hubei-province", "湖北", "湖北省内", "other", 7.2, 1.3, null, null, 0.9, 1.3, ["湖北"]),
        sfUnder20("sfu-jiangxi", "江西", "江西", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["江西"]),
        sfUnder20("sfu-hunan", "湖南", "湖南", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["湖南"]),
        sfUnder20("sfu-anhui", "安徽", "安徽", "all", 8.5, 3.0, 1.5, 2.0, null, null, ["安徽"]),
        sfUnder20("sfu-henan", "河南", "河南", "all", 8.5, 3.0, null, null, 1.5, 2.0, ["河南"]),
        sfUnder20("sfu-shaanxi", "陕西", "陕西", "all", 8.5, 3.0, null, null, 1.5, 2.0, ["陕西"]),
        sfUnder20("sfu-beijing", "北京", "北京", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["北京"]),
        sfUnder20("sfu-fujian", "福建", "福建", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["福建"]),
        sfUnder20("sfu-hebei", "河北", "河北", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["河北"]),
        sfUnder20("sfu-jiangsu", "江苏", "江苏", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["江苏"]),
        sfUnder20("sfu-shandong", "山东", "山东", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["山东"]),
        sfUnder20("sfu-shanghai", "上海", "上海", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["上海"]),
        sfUnder20("sfu-sichuan", "四川", "四川", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["四川"]),
        sfUnder20("sfu-tianjin", "天津", "天津", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["天津"]),
        sfUnder20("sfu-zhejiang", "浙江", "浙江", "all", 8.5, 3.3, null, null, 1.7, 2.2, ["浙江"]),
        sfUnder20("sfu-chongqing", "重庆", "重庆", "all", 8.5, 3.3, null, null, 2.2, 2.8, ["重庆"]),
        sfUnder20("sfu-guangdong", "广东", "广东", "all", 8.5, 3.3, null, null, 2.2, 2.8, ["广东"]),
        sfUnder20("sfu-gansu", "甘肃", "甘肃", "all", 9.1, 3.9, null, null, 2.2, 2.8, ["甘肃"]),
        sfUnder20("sfu-ningxia", "宁夏", "宁夏", "all", 9.1, 3.9, null, null, 1.7, 2.2, ["宁夏"]),
        sfUnder20("sfu-guizhou", "贵州", "贵州", "all", 9.8, 3.3, null, null, 1.7, 2.2, ["贵州"]),
        sfUnder20("sfu-shanxi", "山西", "山西", "all", 9.8, 3.3, null, null, 2.2, 2.8, ["山西"]),
        sfUnder20("sfu-guangxi", "广西", "广西", "all", 9.8, 3.6, null, null, 2.2, 2.8, ["广西"]),
        sfUnder20("sfu-hainan", "海南", "海南", "all", 9.8, 3.6, null, null, 2.2, 2.8, ["海南"]),
        sfUnder20("sfu-liaoning", "辽宁", "辽宁", "all", 9.8, 3.6, null, null, 2.2, 2.8, ["辽宁"]),
        sfUnder20("sfu-yunnan", "云南", "云南", "all", 9.8, 3.9, null, null, 2.3, 2.8, ["云南"]),
        sfUnder20("sfu-qinghai", "青海", "青海", "all", 9.8, 3.9, 2.4, 3.0, null, null, ["青海"]),
        sfUnder20("sfu-neimenggu", "内蒙古", "内蒙古", "all", 9.8, 3.9, 2.4, 3.0, null, null, ["内蒙古"]),
        sfUnder20("sfu-heilongjiang", "黑龙江", "黑龙江", "all", 9.8, 3.9, 2.4, 3.0, null, null, ["黑龙江"]),
        sfUnder20("sfu-jilin", "吉林", "吉林", "all", 9.8, 3.9, 2.4, 3.0, null, null, ["吉林"]),
        sfUnder20("sfu-xinjiang", "新疆", "新疆", "all", 12.4, 6.5, null, null, 4.3, 5.1, ["新疆"]),
      ],
      rows: [
        row("sf-hubei", "湖北", "湖北全境", "all", 40, 23.4, 120, 0.6, 0.4, ["湖北", "武汉"]),
        row("sf-henan-except-pds", "河南", "除平顶山市", "exclude", 40, 39.6, 120, 0.9, 0.6, [], ["平顶山"]),
        row("sf-henan-pds", "河南", "平顶山市", "specific", 40, 41.4, 120, 0.9, 0.6, ["平顶山"]),
        row("sf-jiangxi", "江西", "江西全境", "all", 40, 40.8, 120, 0.9, 0.5, ["江西"]),
        row("sf-hunan-north", "湖南", "岳阳市、长沙市、湘潭市、株洲市、衡阳市、常德市、益阳市、张家界市、怀化市", "specific", 40, 40.8, 120, 0.9, 0.5, ["岳阳", "长沙", "湘潭", "株洲", "衡阳", "常德", "益阳", "张家界", "怀化"]),
        row("sf-hunan-south", "湖南", "郴州市、娄底市、邵阳市、湘西土家族苗族自治州、永州市", "specific", 40, 40.8, 120, 0.9, 0.5, ["郴州", "娄底", "邵阳", "湘西", "永州"]),
        row("sf-shaanxi", "陕西", "陕西全境", "all", 40, 42, 120, 1.1, 0.8, ["陕西", "西安"]),
        row("sf-chongqing", "重庆", "重庆全境", "all", 40, 51, 120, 1, 0.7, ["重庆"]),
        row("sf-shanghai", "上海", "上海全境", "all", 40, 51, 120, 1, 0.6, ["上海"]),
        row("sf-tianjin", "天津", "天津全境", "all", 40, 51, 120, 1, 0.8, ["天津"]),
        row("sf-zhejiang", "浙江", "浙江全境", "all", 40, 51, 120, 1.1, 0.8, ["浙江", "杭州", "宁波", "舟山"]),
        row("sf-fujian", "福建", "福建全境", "all", 40, 51, 120, 1.1, 0.7, ["福建", "福州", "厦门", "宁德"]),
        row("sf-shanxi", "山西", "山西全境", "all", 40, 51, 120, 1.1, 0.8, ["山西"]),
        row("sf-beijing", "北京", "北京", "all", 40, 51, 120, 1.2, 0.7, ["北京"]),
        row("sf-sichuan", "四川", "四川全境", "all", 40, 51, 120, 1.2, 0.9, ["四川", "成都"]),
        row("sf-jiangsu-except", "江苏", "除盐城市、连云港市", "exclude", 40, 51, 120, 1.1, 0.7, [], ["盐城", "连云港"]),
        row("sf-jiangsu-yancheng-lianyungang", "江苏", "盐城市、连云港市", "specific", 40, 51.6, 120, 1.1, 0.7, ["盐城", "连云港"]),
        row("sf-shandong-except", "山东", "除烟台市、威海市", "exclude", 40, 51, 120, 1.1, 0.8, [], ["烟台", "威海"]),
        row("sf-shandong-yantai-weihai", "山东", "烟台市、威海市", "specific", 40, 51.6, 120, 1.1, 0.8, ["烟台", "威海"]),
        row("sf-hebei-except", "河北", "除邯郸市", "exclude", 40, 51, 120, 1.2, 0.8, [], ["邯郸"]),
        row("sf-hebei-handan", "河北", "邯郸市", "specific", 40, 51.6, 120, 1.2, 0.8, ["邯郸"]),
        row("sf-anhui-except", "安徽", "除亳州市/阜阳市", "exclude", 40, 51.6, 120, 1.1, 0.7, [], ["亳州", "阜阳"]),
        row("sf-anhui-bozhou-fuyang", "安徽", "亳州市/阜阳市", "specific", 40, 51.6, 120, 1.2, 0.7, ["亳州", "阜阳"]),
        row("sf-guangxi-south", "广西", "防城港市、崇左市/南宁市、百色市、钦州市、北海市", "specific", 40, 51.6, 120, 1.2, 0.8, ["防城港", "崇左", "南宁", "百色", "钦州", "北海"]),
        row("sf-guangxi-other", "广西", "来宾市/柳州市、桂林市、贺州市/梧州市、贵港市/玉林市、河池市", "specific", 40, 51.6, 120, 1.2, 0.9, ["来宾", "柳州", "桂林", "贺州", "梧州", "贵港", "玉林", "河池"]),
        row("sf-guizhou-main", "贵州", "遵义市、贵阳市、黔南布依族苗族自治州、黔东南苗族侗族自治州、铜仁市、毕节市、六盘水市", "specific", 40, 51, 120, 1.2, 0.8, ["遵义", "贵阳", "黔南", "黔东南", "铜仁", "毕节", "六盘水"]),
        row("sf-guizhou-anshun", "贵州", "安顺市、黔西南布依族苗族自治州", "specific", 40, 53.4, 120, 1.3, 0.8, ["安顺", "黔西南"]),
        row("sf-guangdong-guangzhou", "广东", "广州市", "specific", 40, 58.8, 120, 1.1, 0.6, ["广州"]),
        row("sf-guangdong-except-guangzhou", "广东", "除广州市", "exclude", 40, 61.8, 120, 1.1, 0.7, [], ["广州"]),
        row("sf-hainan", "海南", "海南全境", "all", 40, 62.4, 120, 1.4, 0.9, ["海南", "海口", "三沙"]),
        row("sf-yunnan-except-honghe", "云南", "除红河哈尼族彝族自治州", "exclude", 40, 62.4, 120, 1.4, 0.9, [], ["红河"]),
        row("sf-yunnan-honghe", "云南", "红河哈尼族彝族自治州", "specific", 40, 64.8, 120, 1.5, 1, ["红河"]),
        row("sf-liaoning", "辽宁", "辽宁全境", "all", 40, 63.6, 120, 1.4, 1, ["辽宁", "沈阳", "大连"]),
        row("sf-gansu-except-qingyang", "甘肃", "除庆阳市", "exclude", 40, 64.8, 120, 1.2, 0.9, [], ["庆阳"]),
        row("sf-gansu-qingyang", "甘肃", "庆阳市", "specific", 40, 67.8, 120, 1.3, 1, ["庆阳"]),
        row("sf-ningxia", "宁夏", "宁夏全境", "all", 40, 64.8, 120, 1.2, 0.9, ["宁夏", "银川"]),
        row("sf-qinghai-xining", "青海", "西宁市", "specific", 40, 64.8, 120, 1.3, 0.9, ["西宁"]),
        row("sf-qinghai-east", "青海", "海北藏族自治州、海东市、黄南藏族自治州、海南藏族自治州", "specific", 40, 64.8, 120, 1.3, 1, ["海北", "海东", "黄南", "海南藏族自治州"]),
        row("sf-qinghai-haixi", "青海", "海西蒙古族藏族自治州", "specific", 40, 64.8, 120, 1.4, 0.9, ["海西"]),
        row("sf-qinghai-guoluo-geermu", "青海", "果洛藏族自治州、格尔木", "specific", 40, 67.8, 120, 1.4, 1, ["果洛", "格尔木"]),
        row("sf-qinghai-yushu", "青海", "玉树藏族自治州", "specific", 40, 68.4, 120, 1.7, 1.1, ["玉树"]),
        row("sf-neimenggu-west", "内蒙古", "呼和浩特市、包头市、乌海市、乌兰察布市、鄂尔多斯市、巴彦淖尔市、阿拉善盟", "specific", 40, 64.8, 120, 1.2, 0.9, ["呼和浩特", "包头", "乌海", "乌兰察布", "鄂尔多斯", "巴彦淖尔", "阿拉善"]),
        row("sf-neimenggu-xingan", "内蒙古", "兴安盟", "specific", 40, 77.4, 120, 1.3, 0.9, ["兴安盟"]),
        row("sf-neimenggu-east", "内蒙古", "通辽市、赤峰市", "specific", 40, 78.6, 120, 1.3, 0.9, ["通辽", "赤峰"]),
        row("sf-heilongjiang-east", "黑龙江", "佳木斯市、黑河市、伊春市、七台河市、鸡西市、鹤岗市", "specific", 40, 75.6, 120, 1.5, 0.9, ["佳木斯", "黑河", "伊春", "七台河", "鸡西", "鹤岗"]),
        row("sf-heilongjiang-main", "黑龙江", "哈尔滨市、齐齐哈尔市、牡丹江市、绥化市、大兴安岭地区、大庆市、双鸭山市", "specific", 40, 79.2, 120, 1.6, 1, ["哈尔滨", "齐齐哈尔", "牡丹江", "绥化", "大兴安岭", "大庆", "双鸭山"]),
        row("sf-jilin", "吉林", "吉林全境", "all", 40, 75.6, 120, 1.4, 0.9, ["吉林", "长春"]),
        row("sf-xizang-lasa", "西藏", "拉萨市", "specific", 40, 93, 120, 2.1, 2.1, ["拉萨"]),
        row("sf-xizang-shannan", "西藏", "山南地区", "specific", 40, 110.4, 120, 2.4, 2.1, ["山南"]),
        row("sf-xizang-rikaze", "西藏", "日喀则地区", "specific", 40, 112.8, 120, 2.5, 2.1, ["日喀则"]),
        row("sf-xizang-linzhi", "西藏", "林芝地区", "specific", 40, 115.2, 120, 2.5, 2.1, ["林芝"]),
        row("sf-xinjiang-main", "新疆", "和田地区、阿勒泰地区、博尔塔拉蒙古自治州、克拉玛依市、乌鲁木齐市、奎屯、石河子市、昌吉回族自治州、吐鲁番地区、巴音郭楞蒙古自治州/铁门关市、伊犁哈萨克自治州", "specific", 40, 100.8, 120, 1.7, 1.3, ["和田", "阿勒泰", "博尔塔拉", "克拉玛依", "乌鲁木齐", "奎屯", "石河子", "昌吉", "吐鲁番", "巴音郭楞", "铁门关", "伊犁"]),
        row("sf-xinjiang-kashi", "新疆", "克孜勒苏柯尔克孜自治州、喀什地区", "specific", 40, 100.8, 120, 1.9, 1.4, ["克孜勒苏", "喀什"]),
        row("sf-xinjiang-hami", "新疆", "哈密地区", "specific", 40, 105.6, 120, 1.8, 1.3, ["哈密"]),
        row("sf-xinjiang-tacheng-akesu", "新疆", "塔城地区、阿克苏地区", "specific", 40, 105.6, 120, 1.8, 1.4, ["塔城", "阿克苏"]),
      ],
    },
    {
      id: "deppon",
      name: "德邦",
      shortName: "DP",
      color: "#1d4ed8",
      formula: "deppon-20-60",
      ruleLabel: "首重20斤 / 60斤以内 / 60斤以外",
      source: "IMG_9437.HEIC",
      rows: [
        deppon("dp-hubei", ["湖北"], 13, 0.5, 40, 0.4),
        deppon("dp-henan", ["河南"], 21, 0.85, 50, 0.5),
        deppon("dp-hunan-jiangxi", ["湖南", "江西"], 22, 0.8, 50, 0.55),
        deppon("dp-jiangsu-zhejiang", ["江苏", "浙江"], 25, 0.93, 60, 0.7),
        deppon("dp-anhui", ["安徽"], 26, 1, 60, 0.7),
        deppon("dp-shandong-tianjin", ["山东", "天津"], 26, 0.95, 60, 0.7),
        deppon("dp-hebei", ["河北"], 25, 1.1, 60, 0.7),
        deppon("dp-shanxi-fujian", ["山西", "福建"], 25, 0.95, 60, 0.7),
        deppon("dp-guangdong", ["广东"], 30, 0.95, 65, 0.7),
        deppon("dp-chongqing", ["重庆"], 27, 0.9, 60, 0.7),
        deppon("dp-shaanxi", ["陕西"], 20, 1, 60, 0.7),
        deppon("dp-shanghai", ["上海"], 26, 0.9, 65, 0.75),
        deppon("dp-beijing", ["北京"], 25, 1.25, 65, 0.75),
        deppon("dp-sichuan", ["四川"], 25, 1.15, 65, 0.75),
        deppon("dp-guangxi", ["广西"], 27, 1.15, 70, 0.9),
        deppon("dp-yunnan", ["云南"], 30, 1.2, 70, 0.9),
        deppon("dp-guizhou", ["贵州"], 25, 1.1, 70, 0.9),
        deppon("dp-heilongjiang", ["黑龙江"], 39, 1.35, 80, 1.1),
        deppon("dp-jilin", ["吉林"], 39, 1.3, 80, 1.1),
        deppon("dp-liaoning", ["辽宁"], 32, 1.3, 80, 1.1),
        deppon("dp-hainan", ["海南"], 33, 1.25, 80, 1.2),
        deppon("dp-gansu", ["甘肃"], 33, 1.1, 80, 1.2),
        deppon("dp-ningxia", ["宁夏"], 34, 1.08, 80, 1.2),
        deppon("dp-qinghai", ["青海"], 33, 1.25, 80, 1.2),
        deppon("dp-neimenggu", ["内蒙古"], 32, 1.05, 80, 1.2),
        deppon("dp-xinjiang", ["新疆"], 84, 2.5, 110, 1.5),
        deppon("dp-xizang", ["西藏"], 73, 3, 130, 1.9),
      ],
    },
    {
      id: "jd",
      name: "京东",
      shortName: "JD",
      color: "#dc2626",
      formula: "first-to-threshold",
      ruleLabel: "首重30斤 / 30-120斤 / 120斤以上",
      source: "IMG_9438.HEIC",
      rows: [
        row("jd-hubei", "湖北", "全部", "all", 30, 15.9, 120, 0.51, 0.33, ["湖北", "武汉"]),
        row("jd-hunan-changsha", "湖南", "长沙", "specific", 30, 32.4, 120, 0.84, 0.48, ["长沙"]),
        row("jd-hunan-other", "湖南", "其它", "other", 30, 28.8, 120, 0.84, 0.45),
        row("jd-henan-luohe-zhengzhou-zhumadian", "河南", "漯河、郑州、驻马店", "specific", 30, 30.9, 120, 0.87, 0.51, ["漯河", "郑州", "驻马店"]),
        row("jd-henan-pingdingshan", "河南", "平顶山", "specific", 30, 32.7, 120, 0.87, 0.51, ["平顶山"]),
        row("jd-henan-other", "河南", "其它", "other", 30, 28.8, 120, 0.84, 0.48),
        row("jd-jiangxi-nanchang", "江西", "南昌、萍乡、新余", "specific", 30, 32.7, 120, 0.81, 0.45, ["南昌", "萍乡", "新余"]),
        row("jd-jiangxi-other", "江西", "其它", "other", 30, 31.2, 120, 0.78, 0.45),
        row("jd-beijing", "北京", "全部", "all", 30, 38.1, 120, 1.05, 0.66, ["北京"]),
        row("jd-tianjin", "天津", "全部", "all", 30, 39.3, 120, 0.93, 0.75, ["天津"]),
        row("jd-hebei-qin-tang", "河北", "秦皇岛、唐山", "specific", 30, 39.9, 120, 1.11, 0.75, ["秦皇岛", "唐山"]),
        row("jd-hebei-other", "河北", "其它", "other", 30, 38.1, 120, 1.05, 0.57),
        row("jd-shanghai", "上海", "全部", "all", 30, 39.6, 120, 0.9, 0.75, ["上海"]),
        row("jd-zhejiang-zhoushan", "浙江", "舟山", "specific", 30, 40.8, 120, 1.02, 0.75, ["舟山"]),
        row("jd-zhejiang-other", "浙江", "其它", "other", 30, 37.5, 120, 0.93, 0.69),
        row("jd-jiangsu", "江苏", "全部", "all", 30, 36.9, 120, 0.93, 0.57, ["江苏"]),
        row("jd-anhui-chizhou", "安徽", "池州、淮北、黄山", "specific", 30, 36.9, 120, 0.99, 0.57, ["池州", "淮北", "黄山"]),
        row("jd-anhui-bozhou", "安徽", "亳州", "specific", 30, 36.6, 120, 1.02, 0.6, ["亳州"]),
        row("jd-anhui-fuyang", "安徽", "阜阳", "specific", 30, 38.7, 120, 1.05, 0.6, ["阜阳"]),
        row("jd-anhui-other", "安徽", "其它", "other", 30, 39, 120, 1.02, 0.66),
        row("jd-guangdong-meizhou-zhanjiang", "广东", "梅州、湛江", "specific", 30, 51, 120, 1.08, 0.66, ["梅州", "湛江"]),
        row("jd-guangdong-other", "广东", "其它", "other", 30, 45.6, 120, 0.96, 0.66),
        row("jd-guangxi-nanning", "广西", "南宁", "specific", 30, 40.2, 120, 1.14, 0.75, ["南宁"]),
        row("jd-guangxi-other", "广西", "其它", "other", 30, 37.5, 120, 1.05, 0.81),
        row("jd-shandong-rizhao", "山东", "日照", "specific", 30, 40.8, 120, 1.02, 0.72, ["日照"]),
        row("jd-shandong-other", "山东", "其它", "other", 30, 38.4, 120, 0.96, 0.72),
        row("jd-shanxi-jinzhong-xinzhou", "山西", "晋中、忻州", "specific", 30, 40.8, 120, 1.02, 0.72, ["晋中", "忻州"]),
        row("jd-shanxi-other", "山西", "其它", "other", 30, 36.9, 120, 0.93, 0.81),
        row("jd-neimenggu-hohhot", "内蒙古", "呼和浩特", "specific", 30, 48, 120, 1.02, 0.9, ["呼和浩特"]),
        row("jd-neimenggu-hulunbeier", "内蒙古", "呼伦贝尔", "specific", 30, 65.4, 120, 1.2, 0.84, ["呼伦贝尔"]),
        row("jd-neimenggu-xilingol", "内蒙古", "锡林郭勒盟", "specific", 30, 62.4, 120, 1.2, 0.87, ["锡林郭勒"]),
        row("jd-neimenggu-xingan", "内蒙古", "兴安盟", "specific", 30, 62.1, 120, 1.17, 0.87, ["兴安盟"]),
        row("jd-neimenggu-alashan-eerduosi", "内蒙古", "阿拉善盟、鄂尔多斯", "specific", 30, 53.4, 120, 1.14, 0.87, ["阿拉善", "鄂尔多斯"]),
        row("jd-neimenggu-west", "内蒙古", "巴彦淖尔、包头、乌海、乌兰察布", "specific", 30, 54.9, 120, 1.11, 0.81, ["巴彦淖尔", "包头", "乌海", "乌兰察布"]),
        row("jd-neimenggu-chifeng-tongliao", "内蒙古", "赤峰、通辽", "specific", 30, 59.4, 120, 1.14, 0.84, ["赤峰", "通辽"]),
        row("jd-liaoning-chaoyang-huludao", "辽宁", "朝阳、葫芦岛", "specific", 30, 45.6, 120, 1.2, 0.84, ["朝阳", "葫芦岛"]),
        row("jd-liaoning-other", "辽宁", "其它", "other", 30, 48, 120, 1.26, 0.87),
        row("jd-heilongjiang-hegang-jixi", "黑龙江", "鹤岗、鸡西", "specific", 30, 61.5, 120, 1.41, 0.84, ["鹤岗", "鸡西"]),
        row("jd-heilongjiang-other", "黑龙江", "其它", "other", 30, 58.2, 120, 1.32, 0.84),
        row("jd-jilin-songyuan", "吉林", "松原", "specific", 30, 62.1, 120, 1.35, 0.84, ["松原"]),
        row("jd-jilin-other", "吉林", "其它", "other", 30, 59.1, 120, 1.29, 0.84),
        row("jd-fujian-ningde", "福建", "宁德", "specific", 30, 40.8, 120, 1.02, 0.66, ["宁德"]),
        row("jd-fujian-other", "福建", "其它", "other", 30, 37.8, 120, 0.96, 0.66),
        row("jd-hainan-sansha", "海南", "三沙", "specific", 30, 41.7, 120, 1.11, 0.84, ["三沙"]),
        row("jd-hainan-wanning", "海南", "万宁", "specific", 30, 46.8, 120, 1.26, 0.87, ["万宁"]),
        row("jd-hainan-haikou-lingao", "海南", "海口、临高县", "specific", 30, 49.2, 120, 1.32, 0.9, ["海口", "临高"]),
        row("jd-hainan-other", "海南", "其它", "other", 30, 44.4, 120, 1.2, 0.81),
        row("jd-sichuan-main", "四川", "德阳、绵阳、攀枝花、宜宾、自贡", "specific", 30, 39, 120, 1.2, 0.87, ["德阳", "绵阳", "攀枝花", "宜宾", "自贡"]),
        row("jd-sichuan-other", "四川", "其它", "other", 30, 37.2, 120, 1.14, 0.87),
        row("jd-chongqing", "重庆", "全部", "all", 30, 39.9, 120, 0.87, 0.63, ["重庆"]),
        row("jd-gansu", "甘肃", "全部", "all", 30, 49.2, 120, 1.08, 0.87, ["甘肃", "兰州"]),
        row("jd-ningxia", "宁夏", "全部", "all", 30, 51, 120, 1.08, 0.9, ["宁夏", "银川"]),
        row("jd-shaanxi", "陕西", "全部", "all", 30, 29.7, 120, 0.99, 0.78, ["陕西", "西安"]),
        row("jd-qinghai", "青海", "全部", "all", 30, 50.1, 120, 1.17, 0.93, ["青海", "西宁"]),
        row("jd-guizhou", "贵州", "全部", "all", 30, 36.9, 120, 1.05, 0.72, ["贵州", "贵阳"]),
        row("jd-yunnan-lincang", "云南", "临沧", "specific", 30, 49.2, 120, 1.32, 0.84, ["临沧"]),
        row("jd-yunnan-other", "云南", "其它", "other", 30, 44.4, 120, 1.2, 0.84),
      ],
    },
    {
      id: "post",
      name: "邮政",
      shortName: "EMS",
      color: "#16a34a",
      formula: "post-student-package",
      ruleLabel: "5kg / 10kg / 15kg / 15kg以上",
      source: "IMG_9450.PNG",
      rows: [
        postTier("post-hubei", ["湖北"], 15, 23, 28, 2),
        postTier("post-jiangxi-hunan-anhui-henan", ["江西", "湖南", "安徽", "河南"], 15, 25, 30, 3),
        postTier(
          "post-east-south-main",
          ["上海", "江苏", "浙江", "重庆", "四川", "广东", "北京", "天津", "河北", "山西", "福建", "山东", "陕西", "贵州", "广西"],
          22,
          28,
          36,
          3,
        ),
        postTier("post-northwest-northeast", ["内蒙古", "黑龙江", "吉林", "辽宁", "海南", "云南", "甘肃", "宁夏", "青海"], 28, 38, 48, 4),
        postPerKg("post-xinjiang", ["新疆"], 22, 22),
        postPerKg("post-xizang", ["西藏"], 20, 18),
      ],
    },
  ],
};

function row(id, province, label, scope, firstJin, firstPrice, thresholdJin, rate1, rate2, aliases = [], excludes = []) {
  return { id, province, label, scope, firstJin, firstPrice, thresholdJin, rate1, rate2, aliases, excludes };
}

function deppon(id, provinces, firstPrice, rateToPivot, pivotPrice, rateAfterPivot) {
  return {
    id,
    province: provinces[0],
    provinces,
    label: provinces.join("、"),
    scope: "all",
    firstJin: 20,
    firstPrice,
    pivotJin: 60,
    pivotPrice,
    rateToPivot,
    rateAfterPivot,
    aliases: provinces,
    excludes: [],
  };
}

function sfUnder20(id, province, label, scope, firstPrice, rateTo3, rate3To15, rateAfter15, rate3To20, rateAfter20, aliases = [], excludes = []) {
  return {
    id,
    province,
    label,
    scope,
    firstKg: 1,
    firstPrice,
    rateTo3,
    rate3To15,
    rateAfter15,
    rate3To20,
    rateAfter20,
    aliases,
    excludes,
  };
}

function postTier(id, provinces, price5, price10, price15, rateAfter15) {
  return {
    id,
    kind: "tier",
    province: provinces[0],
    provinces,
    label: provinces.join("、"),
    scope: "all",
    price5,
    price10,
    price15,
    rateAfter15,
    aliases: provinces,
    excludes: [],
  };
}

function postPerKg(id, provinces, firstPrice, rateAfterFirst) {
  return {
    id,
    kind: "per-kg",
    province: provinces[0],
    provinces,
    label: provinces.join("、"),
    scope: "all",
    firstKg: 1,
    firstPrice,
    rateAfterFirst,
    aliases: provinces,
    excludes: [],
  };
}

window.PRICE_DATA.chinaRegionsSource = "中华人民共和国民政部《2023 年中华人民共和国县以上行政区划代码》";
window.PRICE_DATA.chinaRegions = [
  area("北京", ["北京市"]),
  area("天津", ["天津市"]),
  area("河北", ["石家庄市", "唐山市", "秦皇岛市", "邯郸市", "邢台市", "保定市", "张家口市", "承德市", "沧州市", "廊坊市", "衡水市"]),
  area("山西", ["太原市", "大同市", "阳泉市", "长治市", "晋城市", "朔州市", "晋中市", "运城市", "忻州市", "临汾市", "吕梁市"]),
  area("内蒙古", ["呼和浩特市", "包头市", "乌海市", "赤峰市", "通辽市", "鄂尔多斯市", "呼伦贝尔市", "巴彦淖尔市", "乌兰察布市", "兴安盟", "锡林郭勒盟", "阿拉善盟"]),
  area("辽宁", ["沈阳市", "大连市", "鞍山市", "抚顺市", "本溪市", "丹东市", "锦州市", "营口市", "阜新市", "辽阳市", "盘锦市", "铁岭市", "朝阳市", "葫芦岛市"]),
  area("吉林", ["长春市", "吉林市", "四平市", "辽源市", "通化市", "白山市", "松原市", "白城市", "延边朝鲜族自治州"]),
  area("黑龙江", ["哈尔滨市", "齐齐哈尔市", "鸡西市", "鹤岗市", "双鸭山市", "大庆市", "伊春市", "佳木斯市", "七台河市", "牡丹江市", "黑河市", "绥化市", "大兴安岭地区"]),
  area("上海", ["上海市"]),
  area("江苏", ["南京市", "无锡市", "徐州市", "常州市", "苏州市", "南通市", "连云港市", "淮安市", "盐城市", "扬州市", "镇江市", "泰州市", "宿迁市"]),
  area("浙江", ["杭州市", "宁波市", "温州市", "嘉兴市", "湖州市", "绍兴市", "金华市", "衢州市", "舟山市", "台州市", "丽水市"]),
  area("安徽", ["合肥市", "芜湖市", "蚌埠市", "淮南市", "马鞍山市", "淮北市", "铜陵市", "安庆市", "黄山市", "滁州市", "阜阳市", "宿州市", "六安市", "亳州市", "池州市", "宣城市"]),
  area("福建", ["福州市", "厦门市", "莆田市", "三明市", "泉州市", "漳州市", "南平市", "龙岩市", "宁德市"]),
  area("江西", ["南昌市", "景德镇市", "萍乡市", "九江市", "新余市", "鹰潭市", "赣州市", "吉安市", "宜春市", "抚州市", "上饶市"]),
  area("山东", ["济南市", "青岛市", "淄博市", "枣庄市", "东营市", "烟台市", "潍坊市", "济宁市", "泰安市", "威海市", "日照市", "临沂市", "德州市", "聊城市", "滨州市", "菏泽市"]),
  area("河南", ["郑州市", "开封市", "洛阳市", "平顶山市", "安阳市", "鹤壁市", "新乡市", "焦作市", "濮阳市", "许昌市", "漯河市", "三门峡市", "南阳市", "商丘市", "信阳市", "周口市", "驻马店市", "济源市"]),
  area("湖北", ["武汉市", "黄石市", "十堰市", "宜昌市", "襄阳市", "鄂州市", "荆门市", "孝感市", "荆州市", "黄冈市", "咸宁市", "随州市", "恩施土家族苗族自治州", "仙桃市", "潜江市", "天门市", "神农架林区"]),
  area("湖南", ["长沙市", "株洲市", "湘潭市", "衡阳市", "邵阳市", "岳阳市", "常德市", "张家界市", "益阳市", "郴州市", "永州市", "怀化市", "娄底市", "湘西土家族苗族自治州"]),
  area("广东", ["广州市", "韶关市", "深圳市", "珠海市", "汕头市", "佛山市", "江门市", "湛江市", "茂名市", "肇庆市", "惠州市", "梅州市", "汕尾市", "河源市", "阳江市", "清远市", "东莞市", "中山市", "潮州市", "揭阳市", "云浮市"]),
  area("广西", ["南宁市", "柳州市", "桂林市", "梧州市", "北海市", "防城港市", "钦州市", "贵港市", "玉林市", "百色市", "贺州市", "河池市", "来宾市", "崇左市"]),
  area("海南", ["海口市", "三亚市", "三沙市", "儋州市", "五指山市", "琼海市", "文昌市", "万宁市", "东方市", "定安县", "屯昌县", "澄迈县", "临高县", "白沙黎族自治县", "昌江黎族自治县", "乐东黎族自治县", "陵水黎族自治县", "保亭黎族苗族自治县", "琼中黎族苗族自治县"]),
  area("重庆", ["重庆市"]),
  area("四川", ["成都市", "自贡市", "攀枝花市", "泸州市", "德阳市", "绵阳市", "广元市", "遂宁市", "内江市", "乐山市", "南充市", "眉山市", "宜宾市", "广安市", "达州市", "雅安市", "巴中市", "资阳市", "阿坝藏族羌族自治州", "甘孜藏族自治州", "凉山彝族自治州"]),
  area("贵州", ["贵阳市", "六盘水市", "遵义市", "安顺市", "毕节市", "铜仁市", "黔西南布依族苗族自治州", "黔东南苗族侗族自治州", "黔南布依族苗族自治州"]),
  area("云南", ["昆明市", "曲靖市", "玉溪市", "保山市", "昭通市", "丽江市", "普洱市", "临沧市", "楚雄彝族自治州", "红河哈尼族彝族自治州", "文山壮族苗族自治州", "西双版纳傣族自治州", "大理白族自治州", "德宏傣族景颇族自治州", "怒江傈僳族自治州", "迪庆藏族自治州"]),
  area("西藏", ["拉萨市", "日喀则市", "昌都市", "林芝市", "山南市", "那曲市", "阿里地区"]),
  area("陕西", ["西安市", "铜川市", "宝鸡市", "咸阳市", "渭南市", "延安市", "汉中市", "榆林市", "安康市", "商洛市"]),
  area("甘肃", ["兰州市", "嘉峪关市", "金昌市", "白银市", "天水市", "武威市", "张掖市", "平凉市", "酒泉市", "庆阳市", "定西市", "陇南市", "临夏回族自治州", "甘南藏族自治州"]),
  area("青海", ["西宁市", "海东市", "海北藏族自治州", "黄南藏族自治州", "海南藏族自治州", "果洛藏族自治州", "玉树藏族自治州", "海西蒙古族藏族自治州"]),
  area("宁夏", ["银川市", "石嘴山市", "吴忠市", "固原市", "中卫市"]),
  area("新疆", ["乌鲁木齐市", "克拉玛依市", "吐鲁番市", "哈密市", "昌吉回族自治州", "博尔塔拉蒙古自治州", "巴音郭楞蒙古自治州", "阿克苏地区", "克孜勒苏柯尔克孜自治州", "喀什地区", "和田地区", "伊犁哈萨克自治州", "塔城地区", "阿勒泰地区", "石河子市", "阿拉尔市", "图木舒克市", "五家渠市", "北屯市", "铁门关市", "双河市", "可克达拉市", "昆玉市", "胡杨河市", "新星市", "白杨市"]),
  area("台湾", ["台湾省"]),
  area("香港", ["香港特别行政区"]),
  area("澳门", ["澳门特别行政区"]),
];

function area(name, cities) {
  return { name, cities };
}
